spring.datasource.url=jdbc:mysql://localhost:3306/auth_db?useSSL=false&serverTimezone=America/Santiago

spring.datasource.username=root

spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

jwt.secret=8c1814d9ed125dda202a4b2cb4738ed4b59b2b42e3c31787b4c614915fa27d98
jwt.access-token-expiration-ms=900000
jwt.refresh-token-expiration-days=7

